apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment        # the overall name for this deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4                   # number of replica pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1     # the container image:version to utilize
        ports:
        - containerPort: 80
