:useCase: Data Management and Machine Learning

:title: Digital Transformation - SAP Data Intelligence 3.0

:author: Alex Arnoldy
:authorEmail: alex.arnoldy@suse.com
:companyName: SUSE

# :authorGHURL: https://github.com/alexarnoldy/suse-doc/Solution_Guides

:imagesdir: ../media/

ifdef::env-github[]
:imagesdir: {authorGHURL}/blob/master/SA-{useCase}/media/
endif::[]

:CompanyName: SUSE
:ProductName: NA
:ProductNameNoSpaces: NA
:ProductNameCaaSP: CaaS Platform
:ProductNameSES: Enterprise Storage

:SUSEDocType: Solution Guide
:SUSEDocTypeNoSpaces: Solution-Guide

:MarketCategory: Data Management
:MarketCategoryAbbreviation: Data-Management
:SecondaryMarketCategory: Artifical Intelligence / Machine Learning
:SecondaryMarketCategoryAbbreviation: AI/ML

:ISVPartner: SAP
:ISVProductName: Data Intelligence
:ISVProductNameNoSpaces: Data-Intelligence

= {title}
{author}, {companyName} < {authorEMail} >

:favicon:
:doctype: book

[preface]
== Preface

SAP Data Intelligence provides an intuitive, single-pane-of-glass, business-wide view of a broad array of data systems, databases and assets, enabling machine learning, analytics and business intelligence teams to manage an enterprise's entire data landscape through standardized policies and interfaces.

== Introduction

The growth in the amount of business data being collectected continues to accelerate, making utilizing it as much of a challenge as it is an opportunity. While companies are discovering ways to transform their data into products and services that differentiate their business and create new lines of revenue,increasingly they are finding it difficult to fully capitalize on the many datasets they have available to them. At the same time they are coping with the increased cost of managing information that are stored in many, disparate data silos (e.g., cloud object store, on-premise and cloud databases, Hadoop clusters, click-stream and social media feeds). Moreover, maintaining large collections of data adds complexity to their business due to requirements for security, governance, and specialized training. In this light it is not difficult to understand a recent estimation that ~70% of data businesses collected is never utilized. 


== Target Audience 

This paper is directed at professionals involved in both IT Operations and Analytics/Business Intelligence. The recommended framework supplies the requirements to implement SAP’s Data Hub, which is certified on SUSE CaaS Platform.

== Strategy

SAP has long maintained its position as the market leader in mission critical enterprise applications. Supporting SAP with innovation, SUSE has been the market leader for SAP applications for over 20 years. SUSE is the trusted and preferred open source platform for SAP customers who want to unlock data intelligence, drive innovation and run with the best. As an example of this open source mandate, SAP Data Hub is deployed on a Kubernetes-compatible container platform. SUSE CaaS Platform enables you to extend your SUSE Enterprise Linux for SAP environment to container-based application delivery.

== Business Problem

Today’s business leaders are under increasing pressure to manage their business with data-driven decisions. This presents a particular challenge for those executives who strive to bring together the right combination of disparate data sources to unlock new value for their business. This difficulty is compounded by the very nature of how data is collected and stored, which results in independent data silos with clear way for mission critical associations to access them.

Compounding on this challenge is the rapidly expanding ecosphere of data analytics and artificial intelligence applications that consume business data, but often in very specific formats. Gone are the days where company datasets were curated based on a common schema with a small number of dataset views to accomodate a handful of enterprise applications. 

In selecting a data management and analytics platform, businesses need to ensure that their software investment can meet the scale of their current and future application/data landscape, as well as meet current and future data governance needs. 

Equally important in this design is the resiliency and scalability of the underlying infrastructure. Experienced leaders know that enterprise-grade software isn't a solid  investment unless it is built on enterprise-grade infrastructure.

== Business Value

SAP Data Intelligence is a modern, fully containerized solution designed to be deployed on enterprise-grade Kubernetes clusters such as SUSE CaaS Platform. For more than 19 years, SAP has developed its software on SUSE Linux Enterprise Server (SLES) and SUSE solutions such as our CaaS Platform.

SAP Data Intelligence is built on a next-generation data-aggregation model that significantly reduces the need for static data lakes. Instead, SAP Data Intelligence allows for programmatic data extraction and formatting that is executed on the platform where the live data resides. This stands in contrast to the cumbersome practice of running single-use Extract, Load, Transform (ELT) operations. SAP Data Intelligence brings together formatted, refined and cleansed data from multiple sources. The newly integrated dataset can be consumed with Data Intelligence applications such as Leonardo Machine Learning, or by any other enterprise application.

SAP Data Intelligence leverages data processing pipelines, which are built from reusable application components. Data pipelines are computational models that are created on the Data Intelligence platform, but then executed on the data source through the its own, native APIs. Data Pipelines define what data is to be gathered, from which data sources, and how the resultant output should be formatted at the source. Pipelines also specify refinements and cleansing that each stream of data must go through to make it compatible with the other data streams that are being processed by the pipeline. Finally, data pipelines identify which consumer(s) will receive the newly collated data stream. SAP Data Intelligence can persist critical datasets on platform, or simply execute pipelines when required to process and provide the pipeline defined output dataset to the appropriate consumers. This provides advanatages in performance and flexibility, as well as eliminating the need for expensive, scale-limiting data warehouses.

Data pipelines can be created through a graphical user interface to leverage existing data sources such as SAP HANA, SAP Vora, Apache Spark and Apache Hadoop, as well as all major open and closed source OLTP, OLAP and NoSQL databases.

Before implementing a data-analytics solution, consider the specific problem you are working to solve. Below are some use cases for SAP Data Intelligence that can help you zero in on the type of solution you are pursuing.